---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/sign_up":
    post:
      summary: Registers New User
      tags:
      - Registration
      parameters: []
      responses:
        '200':
          description: User Registered
          content: {}
        '400':
          description: invalid request
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                last_name:
                  type: string
                username:
                  type: string
                password:
                  type: string
                password_confirmation:
                  type: string
              required:
              - first_name
              - last_name
              - username
              - password
              - password_confirmation
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
